=== Eltako/enocean-over-ip-twg-notes/json-schema/meta-schemas/components/meta/dependency-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "required": [
        "$schema",
        "required",
        "properties",
        "additionalProperties"
    ],
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "title": "Path to dependency schema file",
            "description": "Path to dependency schema file annotating this depenency file. Use the relative path to the meta folder and the dependency-schema.json.",
            "type": "string",
            "default": "../../../../../../../meta-schemas/components/meta/dependency-schema.json",
            "enum": [
                "../../../../../../../meta-schemas/components/meta/dependency-schema.json"
            ]
        },
        "required": {
            "title": "Holds all property names that are required",
            "description": "Holds the property names that must be set in the dependency file.",
            "type": "array",
            "default": [
                "$schema",
                "number",
                "senderId",
                "repeating",
                "destination",
                "origin",
                "direction"
            ],
            "additionalItems": true,
            "items": [
                {
                    "type": "string",
                    "enum": [
                        "$schema"
                    ]
                },
                {
                    "type": "string",
                    "enum": [
                        "number"
                    ]
                },
                {
                    "type": "string",
                    "enum": [
                        "senderId"
                    ]
                },
                {
                    "type": "string",
                    "enum": [
                        "repeating"
                    ]
                },
                {
                    "type": "string",
                    "enum": [
                        "destination"
                    ]
                },
                {
                    "type": "string",
                    "enum": [
                        "origin"
                    ]
                },
                {
                    "type": "string",
                    "enum": [
                        "direction"
                    ]
                }
            ]
        },
        "properties": {
            "title": "Holds all property and the additional properties of the dependency",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$schema": {
                    "title": "Empty schema property",
                    "description": "Needs to be empty as to not overwrite the information of the parent schema.",
                    "type": "object",
                    "default": {},
                    "enum": [
                        {}
                    ]
                },
                "number": {
                    "title": "Empty number identification property",
                    "description": "Needs to be empty as to not overwrite the information of the parent schema.",
                    "type": "object",
                    "default": {},
                    "enum": [
                        {}
                    ]
                },
                "senderId": {
                    "title": "Empty sender identification property",
                    "description": "Needs to be empty as to not overwrite the information of the parent schema.",
                    "type": "object",
                    "default": {},
                    "enum": [
                        {}
                    ]
                },
                "repeating": {
                    "title": "Empty repeating property",
                    "description": "Needs to be empty as to not overwrite the information of the parent schema.",
                    "type": "object",
                    "default": {},
                    "enum": [
                        {}
                    ]
                },
                "destination": {
                    "title": "Empty destination property",
                    "description": "Needs to be empty as to not overwrite the information of the parent schema.",
                    "type": "object",
                    "default": {},
                    "enum": [
                        {}
                    ]
                },
                "origin": {
                    "title": "Empty origin property",
                    "description": "Needs to be empty as to not overwrite the information of the parent schema.",
                    "type": "object",
                    "default": {},
                    "enum": [
                        {}
                    ]
                },
                "direction": {
                    "title": "Empty direction property",
                    "description": "Needs to be empty as to not overwrite the information of the parent schema.",
                    "type": "object",
                    "default": {},
                    "enum": [
                        {}
                    ]
                },
                "unused": {
                    "$ref": "../../transport-layers/enocean/eep-meta-schema.json#/definitions/unused"
                }
            },
            "patternProperties": {
                "^[a-z][a-zA-Z0-9]*$": {
                    "title": "Holds additional property information",
                    "description": "To extend the functionality of the parent schema.",
                    "type": "object",
                    "required": [
                        "title",
                        "description"
                    ],
                    "additionalProperties": false,
                    "properties": {
                        "title": {
                            "title": "Give your property a title",
                            "description": "Please use a title for your property to better describe what this property stands for.",
                            "type": "string"
                        },
                        "description": {
                            "title": "Give your property a description",
                            "description": "This description can be used to further explain what the property is used for.",
                            "type": "string"
                        },
                        "$ref": {
                            "type": "string",
                            "default": "../../../../../../../meta-schemas/components/xxx-schema.json#/definitions/myProperty#",
                            "pattern": "^../../../../../../../meta-schemas/components/|[a-zA-Z0-9_-]$"
                        },
                        "bitPosition": {
                            "title": "Position of the first bit reserved for the command value",
                            "description": "Possition may be negative if command must be read from the right.",
                            "type": "integer",
                            "default": 0
                        },
                        "bitLength": {
                            "title": "Lenth of the reserved bits for the values",
                            "type": "integer",
                            "default": 8,
                            "minimum": 1
                        },
                        "offset": {
                            "title": "Describes which value corresponds to the zero bit",
                            "type": "integer",
                            "default": 0
                        },
                        "encoding": {
                            "title": "Describes the encoding of the information / how the information is to be interpreted",
                            "type": "string",
                            "enum": [
                                "bigEndian",
                                "littleEndian"
                            ]
                        },
                        "unused": {
                            "anyOf": [
                                {
                                    "type": "array",
                                    "default": [
                                        {
                                            "from": 0,
                                            "to": 0
                                        },
                                        {
                                            "from": 0,
                                            "to": 0
                                        }
                                    ],
                                    "items": {
                                        "type": "object",
                                        "required": [
                                            "from",
                                            "to"
                                        ],
                                        "additionalProperties": false,
                                        "properties": {
                                            "from": {
                                                "type": "integer"
                                            },
                                            "to": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                },
                                {
                                    "type": "object",
                                    "default": {
                                        "from": 0,
                                        "to": 0
                                    },
                                    "required": [
                                        "from",
                                        "to"
                                    ],
                                    "additionalProperties": false,
                                    "properties": {
                                        "from": {
                                            "type": "integer"
                                        },
                                        "to": {
                                            "type": "integer"
                                        }
                                    }
                                },
                                {
                                    "type": "integer",
                                    "default": 0
                                }
                            ]
                        }
                    }
                }
            }
        },
        "additionalProperties": {
            "title": "Are additional properties allowed",
            "description": "If ture properties are allowed to be used that are nod described here.",
            "const": false
        },
        "allOf": {
            "$ref": "../../transport-layers/enocean/eep-meta-schema.json#/definitions/conditional"
        }
    }
}

=== Eltako/enocean-over-ip-twg-notes/json-schema/schemas/enocean/standard/eep/4bs/a5-20-06/dependencies/directionTo.json
{
    "$schema": "../../../../../../../meta-schemas/components/meta/dependency-schema.json",
    "required": [
        "$schema",
        "number",
        "senderId",
        "repeating",
        "destination",
        "origin",
        "direction"
    ],
    "properties": {
        "$schema": {},
        "number": {},
        "senderId": {},
        "repeating": {},
        "destination": {},
        "origin": {},
        "direction": {},
        "valvePosition": {
            "title": "Example property: Reference to a schema definition",
            "description": "Reference to a schema definition located in the \"SchemaDefinitions\" folder. Use this if you have definied a schema or to use predefined generic schemas.",
            "$ref": "../../../../../../../meta-schemas/components/percentage-schema.json#/definitions/valvePosition",
            "bitPosition": 0,
            "bitLength": 8,
            "offset": 0,
            "encoding": "bigEndian",
            "unused": {
                "from": 101,
                "to": 255
            }
        },
        "temperatureSetpoint": {
            "title": "Example property: Reference to a schema definition",
            "description": "Reference to a schema definition located in the \"SchemaDefinitions\" folder. Use this if you have definied a schema or to use predefined generic schemas.",
            "$ref": "../../../../../../../meta-schemas/components/temperature-schema.json#/definitions/temperature0to40CelciusHalfStep#",
            "bitPosition": 0,
            "bitLength": 8,
            "offset": 0,
            "encoding": "bigEndian",
            "unused": {
                "from": 81,
                "to": 255
            }
        },
        "temperatureRCU": {
            "title": "Temperature RCU",
            "description": "Room temperature from room control unit (RCU)",
            "$ref": "../../../../../../../meta-schemas/components/temperature-schema.json#/definitions/temperature0to40CelciusQuarterStep#",
            "bitPosition": 8,
            "bitLength": 8,
            "offset": 0,
            "encoding": "bigEndian",
            "unused":{
                "from": 161,
                "to": 254
            }
        },
        "referenceRun": {
            "title": "Run type",
            "description": "Execute reference-run",
            "$ref": "../../../../../../../meta-schemas/components/direction2-query-schema.json#/definitions/referenceRun#",
            "bitPosition": 16,
            "bitLength": 1,
            "offset": 0,
            "encoding": "bigEndian"
        },
        "commOnInterval": {
            "title": "Communication on interval",
            "description": "Radio duty cycle selection. Find additional information in the Appendix.",
            "$ref": "../../../../../../../meta-schemas/components/direction2-query-schema.json#/definitions/commOnInterval#",
            "bitPosition": 17,
            "bitLength": 3,
            "offset": 0,
            "encoding": "bigEndian"
        },
        "summerBit": {
            "title": "Summer Bit",
            "description": "Initiate summer mode (reduced communication)",
            "$ref": "../../../../../../../meta-schemas/components/direction2-query-schema.json#/definitions/summerBit#",
            "bitPosition": 20,
            "bitLength": 1,
            "offset": 0,
            "encoding": "bigEndian"
        },
        "setPointSelection": {
            "title": "Set point selection",
            "description": "Setpoint selection for DB3",
            "$ref": "../../../../../../../meta-schemas/components/direction2-query-schema.json#/definitions/setPointSelection#",
            "bitPosition": 21,
            "bitLength": 1,
            "offset": 0,
            "encoding": "bigEndian"
        },
        "temperatureSelection": {
            "title": "Temperature Selection",
            "description": "Temperature requested from the actuator (DB1.7...DB1.0, DIR-1, TMP)",
            "$ref": "../../../../../../../meta-schemas/components/direction2-query-schema.json#/definitions/temperatureSelection#",
            "bitPosition": 22,
            "bitLength": 1,
            "offset": 0,
            "encoding": "bigEndian"
        },
        "standby": {
            "title": "Standby",
            "description": "Enter standby mode, refer to Appendix",
            "$ref": "../../../../../../../meta-schemas/components/direction2-query-schema.json#/definitions/standby#",
            "bitPosition": 23,
            "bitLength": 1,
            "offset": 0,
            "encoding": "bigEndian"
        },
        "learnBit": {
            "title": "Learn bit",
            "description": "Is the acctuator in learn mode sending Teach-in telegrams.",
            "$ref": "../../../../../../../meta-schemas/components/direction2-query-schema.json#/definitions/learnBit#",
            "bitPosition": 28,
            "bitLength": 1,
            "offset": 0,
            "encoding": "bigEndian"
        },
        "unused": [
            {
                "from": 24,
                "to": 27
            },
            {
                "from": 29,
                "to": 31
            }
        ]
    },
    "additionalProperties": false,
    "allOf": [
        {
            "if": {
                "properties": {
                    "referenceRun": {
                        "const": "Reference-run"
                    }
                }
            },
            "then": {
                "required": [
                    "$schema",
                    "number",
                    "senderId",
                    "repeating",
                    "destination",
                    "origin",
                    "direction",
                    "referenceRun"
                ],
                "properties": {
                    "$schema": {},
                    "number": {},
                    "senderId": {},
                    "repeating": {},
                    "destination": {},
                    "origin": {},
                    "direction": {},
                    "referenceRun": {},
                    "setPointSelection": {},
                    "temperatureRCU": {},
                    "commOnInterval": {},
                    "valvePosition": {},
                    "temperatureSetpoint": {}
                },
                "additionalProperties": false
            },
            "else": {
                "allOf": [
                    {
                        "if": {
                            "properties": {
                                "referenceRun": {
                                    "const": "Normal operation"
                                }
                            }
                        },
                        "then": {
                            "required": [
                                "$schema",
                                "number",
                                "senderId",
                                "repeating",
                                "destination",
                                "origin",
                                "direction",
                                "referenceRun",
                                "setPointSelection",
                                "commOnInterval"
                            ],
                            "properties": {
                                "$schema": {},
                                "number": {},
                                "senderId": {},
                                "repeating": {},
                                "destination": {},
                                "origin": {},
                                "direction": {},
                                "temperatureRCU": {},
                                "temperatureSetpoint": {},
                                "valvePosition": {},
                                "referenceRun": {},
                                "commOnInterval": {},
                                "summerBit": {},
                                "setPointSelection": {},
                                "temperatureSelection": {},
                                "standby": {},
                                "learnBit": {}
                            },
                            "additionalProperties": false
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "setPointSelection": {
                                    "const": "Valve position mode (0...100%)"
                                }
                            }
                        },
                        "then": {
                            "required": [
                                "$schema",
                                "number",
                                "senderId",
                                "repeating",
                                "destination",
                                "origin",
                                "direction",
                                "temperatureRCU",
                                "valvePosition",
                                "referenceRun",
                                "commOnInterval",
                                "summerBit",
                                "setPointSelection",
                                "temperatureSelection",
                                "standby",
                                "learnBit"
                            ],
                            "properties": {
                                "$schema": {},
                                "number": {},
                                "senderId": {},
                                "repeating": {},
                                "destination": {},
                                "origin": {},
                                "direction": {},
